export const STORAGE_KEY = {
    ADMIN_INFO: "ADMIN_INFO",
    TOKEN: "TOKEN",
    USERS_ONBOARDED: "USERS_ONBOARDED",
    DOCUMENTS_GRAPH: "DOCUMENTS_GRAPH",
    RIDES_GRAPH: "RIDES_GRAPH",
    GET_MANAGE_RIDES: "GET_MANAGE_RIDES",
    SHARERS_EARNINGS: "SHARERS_EARNINGS",
    USERS: "USERS",
    USER_DETAILS: "USER_DETAILS",
    COUPEN_LISTING: "COUPEN_LISTING"
};
